import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// public/styles.css is generated by generate-css.js (a hand-built
// Tailwind-equivalent utility layer — see README "Styling"). Vite serves
// everything in public/ at the site root automatically, both in dev and in
// `vite build`, so no extra config is needed to pick it up.
export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    open: false,
  },
  preview: {
    port: 3000,
  },
  build: {
    outDir: 'dist',
  },
});
